Fixed copy allocround so it shows validation errors when add is pressed
haagahelia/siba-fe pull request #519
Opened 2024-04-17 20:33 UTC by PolinaD31

Also made it so that if there are existing allocrounds, in copy allocroud the initial value of the select allocround to copy is the first existing allocation, since that seemed logical. Can change that back if not a desirable behavior

2024-04-18 07:07 UTC, valju reviewed
Now with copy alloc round for me it shows confirmation question and also confirmation acknowledgement at the same time?

2024-04-19 06:43 UTC, valju requested changes
I think this is still like yesterday? I tested it again and same result, confirmation dialog and success dialog shown simultaneously.

I will put it to "Request changes" so I know not to accidentally test it again :D

2024-04-21 18:49 UTC, PolinaD31 commented
Hey, made some changes and now it should be working fine.

2024-04-22 06:47 UTC, valju approved these changes
Good! The default selected first allocRound is set twice?

2024-04-22 06:47 UTC, merged